version: '3.7'
services:
  mongo:
    image: mongo:5.0.6
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo/data:/data/db
  backend:
    build:
      context: ../backend/
      dockerfile: ../backend/Dockerfile
    ports:
      - ${BACKEND_PORT}:3000
    depends_on:
      - mongo
    volumes:
      - ../backend/:/usr/src/app
      - nodemodules-backend:/usr/src/app/node_modules
  
  frontend:
    restart: always
    container_name: frontend
    build:
      context: ../frontend/
      dockerfile: ../frontend/Dockerfile
    command: yarn serve
    ports:
      - ${FRONTEND_PORT}:8080
    volumes:
      - ../frontend/:/usr/src/client/
      - nodemodules-frontend:/usr/src/client/node_modules

volumes:
  nodemodules-frontend: {}
  nodemodules-backend: {}